name: open_ai_voice_assistant
description: "A new Flutter package that helps you to create voice assistant."
version: 0.0.1
homepage: https://github.com/Abdurrehman-dev/open_ai_voice_assistant
repository: https://github.com/Abdurrehman-dev/open_ai_voice_assistant
issue_tracker: https://github.com/Abdurrehman-dev/open_ai_voice_assistant/issues
license: MIT

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  audio_session: ^0.2.2
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.1.0
  http: ^1.5.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
